### ISSUE TITLE
Enhance the Navigation Bar

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/codeX100#1]
Improve the existing navigation bar by adding hover effects and active link styles to highlight the current page. Ensure the navigation bar is responsive on mobile and tablet devices.

**Tasks:**
- Add hover effects to the links in the navbar.
- Highlight the active link when the user is on a particular page.
- Ensure the navigation bar is mobile-responsive.

**Skills:** HTML, CSS

**Comment by leonyangela** [comment]
Hi, can I work on this issue?

**Comment by leonyangela** [comment]
can you please assign me? thanks

**Comment by arshadpatel** [comment]
It's Ok You can start working on it

**Comment by uzefaqureshi06** [comment]
can  you assign to me i want to work on it

**Comment by arshadpatel** [comment]
Thank you @uzefaqureshi06 for your interest in working on the issue! You can start working on it right away without needing an assignment. Once you've completed the work, feel free to raise a pull request. If it meets the expectations, I'll merge it without delay.

Best of luck, and thanks again for contributing!

**Comment by uzefaqureshi06** [comment]
@arshadpatel    can you assign to me i want to work on it bro I have made  the PR

**Comment by arshadpatel** [comment]
This issue is done @uzefaqureshi06 
You can go with #9 
I have already assigned #9 to you.
