### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/codeX100#10]
The footer currently lacks style. Improve the footer design by adding links to pages like "About Us," "Privacy Policy," and "Terms of Service." Also, include social media icons that link to dummy URLs.

**Tasks:**

- Add links to important pages.
- Design social media icons (e.g., Twitter, GitHub).
- Make the footer responsive.

**Skills:** HTML, CSS

**Comment by harshit1142** [comment]
@arshadpatel Assign me this issue so that I can work on it.

**Comment by arshadpatel** [comment]
@harshit1142 Please start working on it...

**Comment by harshit1142** [comment]
@arshadpatel assign ?

**Comment by harshit1142** [comment]
@arshadpatel from top-right corner , you can assign

**Comment by harshit1142** [comment]
@arshadpatel  ?

**Comment by arshadpatel** [comment]
@harshit1142 Thank you for your interest in working on this issue! I appreciate your enthusiasm. However, I want to clarify that I'm not assigning issues to individuals at this time. Contributors can jump in and start working on the issues directly.

The first person to submit a valid pull request will have their contribution merged. If multiple people submit pull requests for the same issue, I will review all submissions, and if the code is exceptional, I will merge it regardless of who submitted it first.

Feel free to start working on the issue, and I look forward to seeing your contributions!

**Comment by harshit1142** [comment]
@arshadpatel okay.

**Comment by arshadpatel** [comment]
Thank You @Wasid786 for your contribution 👍
