### ISSUE TITLE
 Unique Paths in a Grid with Obstacles

### ISSUE THREAD

**Issue by pratikj697** [arshadpatel/codeX100#28]
Given a 2D grid where some cells may contain obstacles, determine how many unique paths exist to reach the bottom-right corner of the grid from the top-left corner. You can only move either down or right at any point in time.

1. A cell containing 1 represents an obstacle that cannot be passed.
2. A cell containing 0 represents a free space.
3. Your task is to compute the number of unique paths that lead from the top-left corner of the grid (grid[0][0]) to the bottom-right corner (grid[m-1][n-1]).

Constraints:
1. You cannot move into or through an obstacle.
2. You can only move to adjacent cells, either to the right or down.
3. The grid is represented as a 2D list, where grid[i][j] is either 0 (free space) or 1 (obstacle).

Can you please assign this to me @arshadpatel under HactoberFest 2024

**Comment by pratikj697** [comment]
hello @arshadpatel please assign me this issue

**Comment by arshadpatel** [comment]
Sorry @pratikj697 This issue is not related to our current project since we are not dealing with pathfinding or grids in our code. However, I appreciate your suggestion. Unfortunately, this wouldn't fit within our current scope for Hacktoberfest 2024 contributions.
