### ISSUE TITLE
Folder Structure Improvement

### ISSUE THREAD

**Issue by ira-mane** [arshadpatel/codeX100#40]
Hello,

The folder structure of the project can be changed and improved to make it easier to navigate and keep the code clean. We can create two main folders: frontend and backend, and include our respective files in them. Additionally, we can keep a README.md file to document the folder structure. Proper naming of all files is also important to avoid confusion.

**Comment by geekyharsh05** [comment]
@ira-mane Refer this: #27

**Comment by arshadpatel** [comment]
Thank you for your suggestion, @ira-mane  However, @prateek168  has already implemented the changes to the folder structure. We appreciate your contribution and encourage you to check out the latest version of the project.
