### ISSUE TITLE
Fix Login Form Validation

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/codeX100#8]
The login form currently lacks proper validation. Implement validation rules for email format, password length, and error messages for invalid input.

**Tasks:**

- Add email validation (check for proper email format).
- Ensure password has a minimum of 8 characters.
- Display error messages for invalid inputs.

**Skills:** HTML, JavaScript

**Comment by Abhiraj-Sardar** [comment]
hey @arshadpatel ,

I want to work on this issue, please assign this to me.

**Comment by arshadpatel** [comment]
Hiii @Abhiraj-Sardar You can start working on this... No need to wait till I assign... You can share some progress I will merge your changes and assign the task to you....
Thank You for your contributions

**Comment by Abhiraj-Sardar** [comment]
Hi @arshadpatel ,

I just made a Pull Request. please review and merge it.

This is how it looks like👇
![demo1](https://github.com/user-attachments/assets/f88be2cf-d678-4567-a66d-bcbc2a686796)

Thank You

**Comment by arshadpatel** [comment]
I have reviewed and made the necessary suggestions to ensure the login and signup pages meet expectations.

Thank You @Abhiraj-Sardar for your contributions

**Comment by juhdakd** [comment]
@arshadpatel  hi,I made some attempts, please check it out, and if you can, merge it. #50

**Comment by arshadpatel** [comment]
We are planning to make login page something like this

![image](https://github.com/user-attachments/assets/c5f6bce9-bbf3-4e30-8c33-73e774252b41)

**Comment by juhdakd** [comment]
@arshadpatel Thank you for your feedback. I have decided not to continue with this PR. I greatly appreciate the opportunity to collaborate this time and look forward to more opportunities to work together in the future.

**Comment by prateek168** [comment]
@arshadpatel can you assign this to me ?

**Comment by arshadpatel** [comment]
Assigned!!!
